language: php
php:
#  - 7.1 # avoid PHPUnit_Framework_TestCase -> PHPUnit\Framework\TestCase
#  - 7.0 # for now
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "chat.freenode.net#cloudi"
    on_success: change
    on_failure: always
