language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "chat.freenode.net#cloudi"
    on_success: change
    on_failure: always
