language: php
php:
  - 7.1
  - 7.0
#  - hhvm # phpunit 6.5.2 failed with HipHop VM 3.28.3
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "chat.freenode.net#cloudi"
    on_success: change
    on_failure: always
