dist: trusty
language: php
php:
  - 7.1
  - 7.0
  - hhvm
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "chat.freenode.net#cloudi"
    on_success: change
    on_failure: always
